course_colleged = {
    ('EEDU_302', 'Entrepreneurship II', 'Junior'): 'COBA',
    ('ACCT_102', 'Introduction Accounting', 'Freshmen'): 'COBA',
    ('ACCT_102', 'Introduction to Accounting', 'Freshmen'): 'COBA',
    ('ACCT_201', 'Principles of Accounting I', 'Sophomore'): 'COBA',
    ('ACCT_202', 'Principles of Accounting II', 'Sophomore'): 'COBA',
    ('ACCT_302', 'Intermediate Accounting II', 'Junior'): 'COBA',
    ('ACCT_304', 'Cost Accounting II', 'Junior'): 'COBA',
    ('ACCT_314', 'Managerial Accounting', 'Junior'): 'COBA',
    ('ACCT_402', 'Advanced Accounting II', 'Senior'): 'COBA',
    ('ACCT_404', 'Auditing II', 'Senior'): 'COAB',
    ('ACCT_404', 'Principles of Auditing II', 'Senior'): 'COBA',
    ('ACCT_408', 'Accounting Theory & Practice', 'Senior'): 'COBA',
    ('ACCT_408', 'Accounting Theory and Practice', 'Senior'): 'COAB',
    ('ACCT_410', 'Budgeting and Taxation', 'Senior'): 'COBA',
    ('ACCT_410', 'Public Budgeting and Taxation', 'Senior'): 'COAB',
    ('ACCT_430', 'Senior Accounting Project Writing', 'Senior'): 'COBA',
    ('ACCT_430', 'Senior Accounting Research', 'Senior'): 'COAB',
    ('AGR_122', 'Practicum II', 'Freshmen'): 'CFAS',
    ('AGR_202', 'Agricultural Physics', 'Sophomore'): 'CFAS',
    ('AGR_204', 'Agricultural Marketing', 'Sophomore'): 'CFAS',
    ('AGR_206', 'Agricultural Statistics & Experimental Design', 'Sophomore'): 'CFAS',
    ('AGR_206', 'Agricultural Statistics and Experimental Design', 'Sophomore'): 'CFAS',
    ('AGR_222', 'Practicum IV', 'Sophomore'): 'CFAS',
    ('AGR_306', 'Plant Genetics', 'Junior'): 'CFAS',
    ('AGR_308', 'Agriculture and Climate Change', 'Junior'): 'CFAS',
    ('AGR_308·', 'Agriculture & Climate Change', 'Junior'): 'CFAS',
    ('AGR_322', 'Seminar II', 'Junior'): 'CFAS',
    ('AGR_327', 'AAE: Lowland/Upland Rice Production & Mgt.', 'Junior'): 'CFAS',
    ('AGR_327', 'Low Land/Upland Rice Production and Management', 'Junior'): 'CFAS',
    ('AGR_332', 'Plant Physiology', 'Junior'): 'CFAS',
    ('AGR_352', 'Post Harvest Management & Technology', 'Junior'): 'CFAS',
    ('AGR_352', 'Post-harvest Management & Technology', 'Junior'): 'CFAS',
    ('AGR_404', 'Agriculture Farm Management', 'Senior'): 'CFAS',
    ('AGR_404', 'Farm Management/Entrepreneurship & Microenterprise', 'Senior'): 'CFAS',
    ('AGR_411', 'AAE: Oil-palm Production & Management', 'Senior'): 'CFAS',
    ('AGR_411', 'Oil Palm Production and Management', 'Senior'): 'CFAS',
    ('AGR_424', 'Vegetable Production and Management', 'Senior'): 'CFAS',
    ('AGR_426', 'Senior Research & Presentation', 'Senior'): 'CFAS',
    ('AGR_426', 'Senior Research Development Project', 'Senior'): 'CFAS',
    ('AGR_433', 'AAE: Animal Production and Management', 'Senior'): 'CFAS',
    ('AGR_433', 'Animal Production and Management', 'Senior'): 'CFAS',
    ('AGR_434', 'AAE: Cassava Production, Mgt. & Processing', 'Senior'): 'CFAS',
    ('AGR_434', 'Cassava Production and Rice Management and Processing', 'Senior'): 'CFAS',
    ('AGR_452', 'Plant Pathology & Weed Science', 'Senior'): 'CFAS',
    ('AGR_452', 'Plant Pathology and Weed Science', 'Senior'): 'CFAS',
    ('AGR_454', 'Tropical Food Crops', 'Senior'): 'CFAS',
    ('AGR_468', 'Animal Health & Disease Control', 'Senior'): 'CFAS',
    ('AGR_468', 'Animal Health and Disease Control', 'Senior'): 'CFAS',
    ('BFIN_302', 'Corporate Finance', 'Junior'): 'COBA',
    ('BFIN_302', 'Financial institutions & Markets', 'Junior'): 'COAB',
    ('BFIN_304', 'Portfolio Theory & Management', 'Junior'): 'COAB',
    ('BFIN_304', 'Portfolio Theory &Management', 'Junior'): 'COBA',
    ('BFIN_402', 'Financial Planning &control', 'Senior'): 'COBA',
    ('BFIN_404', 'Treasury Management', 'Senior'): 'COBA',
    ('BFIN_404', 'Treasury management', 'Senior'): 'COAB',
    ('BFIN_406', 'Financial Planning & Control', 'Senior'): 'COAB',
    ('BFIN_412', 'International Banking & Finance', 'Senior'): 'COBA',
    ('BFIN_430', 'Project Writing', 'Senior'): 'COBA',
    ('BFIN_430', 'Senior Banking Project Writing', 'Senior'): 'COAB',
    ('BIO_0202A', 'General Zoology', 'Unknown'): 'COAS',
    ('BIO_101', 'General Biology I', 'Freshmen'): 'COAS',
    ('BIO_101', 'General Biology', 'Freshmen'): 'COAS',
    ('BIO_202', 'Anatomy & Physiology for Health Sciences I', 'Sophomore'): 'COHS',
    ('BIO_202', 'Anatomy and Physiology II', 'Sophomore'): 'COHS',
    ('BIO_202A', 'General Zoology', 'Sophomore'): 'COAS',
    ('BIO_203', 'Microbiology for Health Sciences', 'Sophomore'): 'COHS',
    ('BIO_203', 'Microbiology', 'Sophomore'): 'COHS',
    ('BIO_206', 'Bio-Statistics', 'Sophomore'): 'COAS',
    ('BIO_302', 'Animal Parasitology', 'Junior'): 'COAS',
    ('BIO_304', 'Histology And Micro Techniques', 'Junior'): 'COHS',
    ('BIO_304', 'Histology and Microtechniques', 'Junior'): 'COAS',
    ('BIO_306', 'Cytology And Pathology', 'Junior'): 'COHS',
    ('BIO_306', 'Cytology and Pathology', 'Junior'): 'COAS',
    ('BIO_308', 'Vertebrate Embryology', 'Junior'): 'COHS',
    ('BIO_308', 'Vetebrate Embryology', 'Junior'): 'COAS',
    ('BIO_376', 'Animal Behavior and Function', 'Junior'): 'COAS',
    ('BIO_377', 'Botany', 'Junior'): 'COAS',
    ('BIO_378', 'Integrated Science', 'Junior'): 'COAS',
    ('BIO_402', 'Biochemistry', 'Senior'): 'COAS',
    ('BIO_404', 'Immunology', 'Senior'): 'COAS',
    ('BIO_406', 'Genetics & Genomics', 'Senior'): 'COAS',
    ('BIO_406', 'Genetics and Genomics', 'Senior'): 'COHS',
    ('BIO_408', 'Research Project II', 'Senior'): 'COAS',
    ('BIO_472', 'Biostatistics', 'Senior'): 'COAS',
    ('BUSA_202', 'Principles of  Management', 'Sophomore'): 'COBA',
    ('BUSA_202', 'Principles of Management', 'Sophomore'): 'COBA',
    ('BUSA_302', 'Human Resource Management', 'Junior'): 'COBA',
    ('BUSA_304', 'Marketing and Sales Production', 'Junior'): 'COBA',
    ('BUSA_314', 'Operation Research', 'Junior'): 'COBA',
    ('BUSA_314', 'Operations Research', 'Junior'): 'COAB',
    ('BUSA_402', 'Business Ethics', 'Senior'): 'COBA',
    ('BUSA_404', 'International Marketing', 'Senior'): 'COBA',
    ('BUSA_406', 'Purchasing Admin. & Material Management', 'Senior'): 'COBA',
    ('BUSA_406', 'Purchasing Administration & Material Management', 'Senior'): 'COAB',
    ('BUSA_408', 'Quality Management', 'Senior'): 'COBA',
    ('BUSA_430', 'Project Writing', 'Senior'): 'COBA',
    ('BUSA_430', 'Senior business Project Writing', 'Senior'): 'COAB',
    ('CENG_302', 'Surveying II', 'Junior'): 'COET',
    ('CENG_402', 'Structural Analysis and Design II', 'Senior'): 'COET',
    ('CENG_406', 'Geotechnical Engineering', 'Senior'): 'COET',
    ('CENG_408', 'Introduction to Thermodynamics', 'Senior'): 'COET',
    ('CENG_410', 'Civil Engineering Lab II', 'Senior'): 'COET',
    ('CENG_410', 'Civil Lab II', 'Senior'): 'COET',
    ('CENG_502', 'Structural Analysis and Design IV', 'Senior'): 'COET',
    ('CENG_504', 'Highway Engineering II', 'Senior'): 'COET',
    ('CENG_508', 'Environmental /Sanitary  II', 'Senior'): 'COET',
    ('CENG_508', 'Environmental /Sanitary II (Waste water Management)', 'Senior'): 'COHS',
    ('CENG_508', 'Environmental /Sanitary II', 'Senior'): 'COET',
    ('CENG_510', 'CE Seminar', 'Senior'): 'COET',
    ('CHEM_101', 'Principles of Chemistry', 'Freshmen'): 'COAS',
    ('CHEM_102', 'Organic Chemistry I', 'Freshmen'): 'COAS',
    ('CHEM_102', 'Organic Chemistry with Biochemistry', 'Freshmen'): 'COAS',
    ('CHEM_202', 'Inorganic Chemistry', 'Sophomore'): 'COAS',
    ('CHEM_202', 'Inorganic', 'Sophomore'): 'COAS',
    ('CHEM_204', 'Environmental Chemistry', 'Sophomore'): 'COAS',
    ('CHEM_376', 'Introduction to Bio-Chemistry', 'Junior'): 'COAS',
    ('CHEM_377', 'Analytical Chemistry', 'Junior'): 'COAS',
    ('CHEM_476', 'Introduction to Industrial Chemistry', 'Senior'): 'COAS',
    ('CSENG_302', 'Web Programming and Development', 'Junior'): 'COET',
    ('CSENG_304', 'Advance Java Programming', 'Junior'): 'COET',
    ('CSENG_304', 'Advanced Java Programming', 'Junior'): 'COET',
    ('CSENG_306', 'Computer Science Professional Ethics', 'Junior'): 'COET',
    ('CSENG_308', 'Introduction To Software Engineering', 'Junior'): 'COET',
    ('CSENG_308', 'Introduction to Software Engineering', 'Junior'): 'COET',
    ('CSENG_310', 'Introduction to Databases', 'Junior'): 'COET',
    ('CSENG_402', 'Software Engineering Comprehensive Practice', 'Senior'): 'COET',
    ('CSENG_404', 'Advance Operating Systems', 'Senior'): 'COET',
    ('CSENG_404', 'Advanced Operating System', 'Senior'): 'COET',
    ('CSENG_406', 'Digital Computer Circuits', 'Senior'): 'COET',
    ('CSENG_408', 'Data Communication and Networking I', 'Senior'): 'COET',
    ('CSENG_410', 'Network Principles and Computer Security', 'Senior'): 'COET',
    ('CSENG_502', 'Data Communications and Networking II', 'Senior'): 'COET',
    ('CSENG_504', 'Compiler Design', 'Senior'): 'COET',
    ('CSENG_506', 'CSE Seminar', 'Senior'): 'COET',
    ('CSENG_506', 'Computer Science Engineering  Seminar', 'Senior'): 'COET',
    ('CSENG_506', 'Computer Science Engineering Seminar', 'Senior'): 'COET',
    ('CSE_102', 'Computer Literacy', 'Freshmen'): 'COET',
    ('ECD_262', 'Mathematics for Teachers in Early Childhood and Primary Education', 'Sophomore'): 'COED',
    ('ECD_262', 'Mathematics for Teachers in Early Years’Classrooms', 'Sophomore'): 'COED',
    ('ECD_264', 'Principles & Foundations of Education', 'Sophomore'): 'COED',
    ('ECD_264', 'Principles and Foundations of Early Childhood Development and Education', 'Sophomore'): 'COED',
    ('ECD_364', 'Teaching Language Arts Through Literature, Performance and Visual Arts in Early Childhood Setting', 'Junior'): 'COED',
    ('ECD_364', 'Teaching Language Arts Thru Literature', 'Junior'): 'COED',
    ('ECD_366', 'Method of Learning Science, Mathematics and Literacy', 'Junior'): 'COED',
    ('ECD_366', 'Methods of Teaching Science, Mathematics and Literacy inECD', 'Junior'): 'COED',
    ('ECD_368', 'Social Studies and Social Exploration in Pre-Kindergarten to 6th Grade Classrooms in Liberian Schools', 'Junior'): 'COED',
    ('ECD_368', 'Social Studies and Social Exploration in the Pre-K Classrooms in Liberian schools', 'Junior'): 'COED',
    ('ECD_369', 'Infant and Toddlers Group Care', 'Junior'): 'COED',
    ('ECD_369', 'Infants and Toddlers Group Care', 'Junior'): 'COED',
    ('ECD_462', 'Curriculum and Instruction Supervised Student Teaching - 3rd to 6th Grade', 'Senior'): 'COED',
    ('ECD_462', 'Curriculum and Instruction Supervised Student Teaching II', 'Senior'): 'COED',
    ('ECD_464', 'Curriculum and Instruction/Seminar II', 'Senior'): 'COED',
    ('ECD_464', 'Curriculum and Instruction: Seminar I', 'Senior'): 'COED',
    ('ECD_467', 'Creative Activities for Children: Teacher Made Materials for Play and Subject Area Skills Development', 'Senior'): 'COED',
    ('ECON_202', 'Principles of Economics II', 'Sophomore'): 'COBA',
    ('ECON_302', 'Intermediate Microeconomic Analysis II', 'Junior'): 'COBA',
    ('ECON_304', 'Intermediate Macroeconomic Analysis II', 'Junior'): 'COBA',
    ('ECON_306', 'Survey of Liberian Economy', 'Junior'): 'COAB',
    ('ECON_306', 'Survey of Liberian economy', 'Junior'): 'COBA',
    ('ECON_308', 'Research Methodology', 'Junior'): 'COBA',
    ('ECON_314', 'Business & Econ. Statistics II', 'Junior'): 'COBA',
    ('ECON_314', 'Business and Economics Statistics II', 'Junior'): 'COAB',
    ('ECON_402', 'Public Finance', 'Senior'): 'COBA',
    ('ECON_404', 'Managerial Economics', 'Senior'): 'COBA',
    ('ECON_408', 'Econometrics and Time Series', 'Senior'): 'COBA',
    ('ECON_412', 'Industrial Economics', 'Senior'): 'COAB',
    ('ECON_412', 'International Economic Analysis', 'Senior'): 'COBA',
    ('ECON_430', 'Project Writing', 'Senior'): 'COBA',
    ('EDUP_262', 'Mathematics for Teachers in Primary Classrooms', 'Sophomore'): 'COED',
    ('EDUP_262', 'Mathematics for Teachers in Primary School', 'Sophomore'): 'COED',
    ('EDUP_264', 'Principles and Foundations of Primary Education', 'Sophomore'): 'COED',
    ('EDUP_364', 'Teaching Language Arts Through Literature, Performance and Visual Arts in Primary Curriculum', 'Junior'): 'COED',
    ('EDUP_364', 'Teaching Language Arts Through Literature, Performance and Visual Artsin Primary Curriculum', 'Junior'): 'COED',
    ('EDUP_366', 'Methods of Teaching Science, Mathematics and Literacy in Primary Classroom', 'Junior'): 'COED',
    ('EDUP_366', 'Methods of Teaching Science, Mathematics and Literacy in Primary', 'Junior'): 'COED',
    ('EDUP_368', 'Social Studies and Social Exploration in Primary Classroom', 'Junior'): 'COED',
    ('EDUP_368', 'Social Studies and Social Exploration in Primary Classrooms in Liberian schools', 'Junior'): 'COED',
    ('EDUP_369', 'Care for Primary Pupils', 'Junior'): 'COED',
    ('EDUP_369', 'Infants and Toddlers Group Care', 'Junior'): 'COED',
    ('EDUP_462', 'Curriculum and Instruction Supervised Student Teaching II', 'Senior'): 'COED',
    ('EDUP_462', 'Curriculum and Instruction: Supervised Student Teaching II', 'Senior'): 'COED',
    ('EDUP_464', 'Curriculum and Instruction: Seminar I', 'Senior'): 'COED',
    ('EDUP_464', 'Curriculum and Instruction: Seminar II', 'Senior'): 'COED',
    ('EDUP_467', 'Creative Activities for Children: Teacher Made Materials for Play and Subject Area Skills Development', 'Senior'): 'COED',
    ('EDUP_467', 'Creative Activities for Primary Pupils: Teacher Made Materials for Play and Subject Area Skills Development', 'Senior'): 'COED',
    ('EDU_252', 'Social World of thr Child', 'Sophomore'): 'COED',
    ('EDU_252', 'The Social World of the Child and Adolescent', 'Sophomore'): 'COED',
    ('EDU_254', 'Speech, Language and Learning', 'Sophomore'): 'COED',
    ('EDU_256', 'School Pedagogy and Social Justice', 'Sophomore'): 'COED',
    ('EDU_258', 'Principles and Foundation of Education', 'Sophomore'): 'COED',
    ('EDU_350', 'Ethnographic Studies in Rural Communities', 'Junior'): 'COED',
    ('EDU_350', 'Ethnographic Studies in Rural areas', 'Junior'): 'COED',
    ('EDU_354', 'Classroom Management', 'Junior'): 'COED',
    ('EDU_354', 'Classroom Management:Designing & Managing the Learning Environment', 'Junior'): 'COED',
    ('EDU_358', 'Educational Administration and Leadership', 'Junior'): 'COED',
    ('EDU_358', 'Educational Administration', 'Junior'): 'COED',
    ('EDU_380', 'Methods of Teaching Science in Jr. and Sr. High School', 'Junior'): 'COED',
    ('EDU_380', 'Methods of Teaching Science in Junior and Senior Secondary Schools', 'Junior'): 'COED',
    ('EDU_382', 'Methods of Teaching Engl & Lite', 'Junior'): 'COED',
    ('EDU_382', 'Methods of Teaching Mathematics', 'Junior'): 'COED',
    ('EDU_383', 'Method (s) Teaching English and Literature in Jr. and Sr. High School', 'Junior'): 'COED',
    ('EDU_383', 'Method (s) of Teaching English and Literature in Jr. and Sr. High School', 'Junior'): 'COED',
    ('EDU_383', 'Methods of Teaching English and Literature in Junior and Senior Secondary Schools', 'Junior'): 'COED',
    ('EDU_384', 'Method of Teaching History in Jr. and Sr. High School', 'Junior'): 'COED',
    ('EDU_384', 'Methods of Teaching History in Junior and Senior Secondary Schools', 'Junior'): 'COED',
    ('EDU_458', 'Advocacy, Networking and Collaboration in School and Community', 'Senior'): 'COED',
    ('EDU_458', 'Advocacy, Networking and Collaboration in Schools', 'Senior'): 'COED',
    ('EDU_459', 'Perspective in Science and Mathematics', 'Senior'): 'COED',
    ('EDU_459', 'Perspectives in Science and Mathematics', 'Senior'): 'COED',
    ('EDU_476', 'Curriculum and Instruction Student Teaching II', 'Senior'): 'COED',
    ('EDU_476', 'Curriculum and Instruction Supervised Student Teaching II', 'Senior'): 'COED',
    ('EDU_478', 'Curriculum and Instruction: Seminar II', 'Senior'): 'COED',
    ('EDU_478', 'Seminar II', 'Senior'): 'COED',
    ('EEDU_302', 'Entrepreneurship Education II', 'Junior'): 'COBA',
    ('EED_302', 'Entrepreneurship Education II', 'Junior'): 'COAB',
    ('EENG_302', 'Eelectrical Network', 'Junior'): 'COET',
    ('EENG_302', 'Egineering Electrodynamics', 'Junior'): 'COET',
    ('EENG_302', 'Engineering Electrodynamics', 'Junior'): 'COET',
    ('EENG_304', 'Engineering Electrodynamics', 'Junior'): 'COET',
    ('EENG_304', 'Network II', 'Junior'): 'COET',
    ('EENG_306', 'Electrical Engineering Lab I', 'Junior'): 'COET',
    ('EENG_306', 'Electrical Fundamentals', 'Junior'): 'COET',
    ('EENG_308', 'Electrical Power and Machines', 'Junior'): 'COET',
    ('EENG_308', 'Electrical power and machines', 'Junior'): 'COET',
    ('EENG_402', 'Electronics II (Degital)', 'Senior'): 'COET',
    ('EENG_402', 'Electronics II (Digital)', 'Senior'): 'COET',
    ('EENG_404', 'Communication Theory', 'Senior'): 'COET',
    ('EENG_404', 'Electrical Engineering Senior Project', 'Senior'): 'COET',
    ('EENG_406', 'Electrical Machinery', 'Senior'): 'COET',
    ('EENG_408', 'Engineering Instrumentation and Measurement', 'Senior'): 'COET',
    ('EENG_408', 'Instrumentation and Measurement', 'Senior'): 'COET',
    ('EENG_500', 'EE Seminar', 'Senior'): 'COET',
    ('EENG_500', 'Electrical Engineering Seminar (Electrical)', 'Senior'): 'COET',
    ('EENG_502', 'Power System Protection', 'Senior'): 'COET',
    ('EENG_502', 'Power Systems Protection', 'Senior'): 'COET',
    ('EENG_504', 'High Voltage Engineering', 'Senior'): 'COET',
    ('EENG_505', 'EE Senior Design Project', 'Senior'): 'COET',
    ('EENG_505', 'Electrical Engineering Project Design', 'Senior'): 'COET',
    ('EENG_506', 'Optical Fiber Communication Systems', 'Senior'): 'COET',
    ('EENG_506', 'Optical Fibre Communication', 'Senior'): 'COET',
    ('EENG_508', 'Electric Machines and Drives', 'Senior'): 'COET',
    ('EENG_508', 'Electrical Machine sand Drives', 'Senior'): 'COET',
    ('ENGL_101', 'College grammar and Phonetics', 'Freshmen'): 'COAS',
    ('ENGL_101', 'English Grammar and Phonetics', 'Freshmen'): 'COAS',
    ('ENGL_102', 'Academic Reading & Writing', 'Freshmen'): 'COAS',
    ('ENGL_102', 'Academic Reading and Writing', 'Freshmen'): 'COAS',
    ('ENGL_204', 'Introduction to Literature', 'Sophomore'): 'COAS',
    ('ENGL_376', 'Eco-Literature', 'Junior'): 'COAS',
    ('ENGL_377', 'Advanced Academic Reading and Writing', 'Junior'): 'COAS',
    ('ENGL_378', 'Gender, Feminism and Contemporary Literature', 'Junior'): 'COAS',
    ('ENGL_472', '18th Century Literature and Early English Novel Period', 'Senior'): 'COAS',
    ('ENGL_472', '18th century Literature and Early English Novel', 'Senior'): 'COAS',
    ('ENGL_474', 'Poetry and Creative Non-Fiction Writing', 'Senior'): 'COAS',
    ('ENVS_201', 'Introduction to Environmental Science', 'Sophomore'): 'COAS',
    ('ENVS_201', 'Introduction to Environmental Sciene', 'Sophomore'): 'COAS',
    ('ENVS_202', 'Ecology and Biodiversity', 'Sophomore'): 'COAS',
    ('ENVS_204', 'Environmental Chemistry', 'Sophomore'): 'COAS',
    ('ENVS_206', 'Environmental Physics', 'Sophomore'): 'COAS',
    ('ENVS_208', 'Statistics For Environmental Science', 'Sophomore'): 'COAS',
    ('ENVS_208', 'Statistics for Environmental Science', 'Sophomore'): 'COAS',
    ('ENVS_302', 'Atmosphere, Ocean & Climate Change', 'Junior'): 'COAS',
    ('ENVS_302', 'Atmosphere, Ocean, and Climate Change', 'Junior'): 'CFAS',
    ('ENVS_304', 'Natural Resource Management', 'Junior'): 'COAS',
    ('ENVS_306', 'Waste Management', 'Junior'): 'COAS',
    ('ENVS_308', 'Environmental Pollution', 'Junior'): 'COAS',
    ('ENVS_312', 'Junior Seminar II', 'Junior'): 'CFAS',
    ('ENVS_318', 'Forest Ecologgy and Conservation', 'Junior'): 'CFAS',
    ('ENVS_318', 'Forest Ecology and Conservation', 'Junior'): 'COAS',
    ('ENVS_402', 'Hazards and Disaster Management', 'Senior'): 'COAS',
    ('ENVS_404', 'Environmental Impact Assessment', 'Senior'): 'COAS',
    ('ENVS_406', 'Conservation Biology', 'Senior'): 'COAS',
    ('ENVS_408', 'Environmental Laws and Policy', 'Senior'): 'COAS',
    ('ENVS_420', 'Project/Internship', 'Senior'): 'COAS',
    ('FREN_202', 'Intermediate French', 'Sophomore'): 'COAS',
    ('GCED_384', 'Intervening with Displaced and Marginalized Population', 'Junior'): 'COHS',
    ('GCED_384', 'Intervening with Displaced and Marginalized Populations', 'Junior'): 'COED',
    ('GCED_385', 'Expressive Therapies in Guidance & Counseling', 'Junior'): 'COED',
    ('GCED_385', 'Expressive Therapies in Guidiance and Counseling', 'Junior'): 'COHS',
    ('GCED_386', 'Parents, Family and Group Processes', 'Junior'): 'COED',
    ('GCED_388', 'Group Processes for Guidance Counselors', 'Junior'): 'COED',
    ('GCED_480', 'Crisis Intervention, Conflict Resolution and Mediation', 'Senior'): 'COED',
    ('GCED_482', 'Guidance and Counseling Clinical Practice II: Supervised Field Experience in Secondary High Setting', 'Senior'): 'COHS',
    ('GCED_482', 'Supervised Clinical Practice II', 'Senior'): 'COED',
    ('GCED_484', 'Clinical Seminar II', 'Senior'): 'COED',
    ('GCED_484', 'Guidance and Counseling Clinical Seminar II', 'Senior'): 'COHS',
    ('GCED_486', 'Social, Cultural and Identity Awareness', 'Senior'): 'COED',
    ('GENG_106', 'Introduction to Engineering Analysis and Design', 'Freshmen'): 'COET',
    ('GENG_106', 'Introduction to Engineering Design and Analysis', 'Freshmen'): 'COET',
    ('GENG_202', 'Engineering Graphics/CAD I', 'Sophomore'): 'COET',
    ('GENG_302', 'AUTOCAD 2', 'Junior'): 'COET',
    ('GENG_302', 'Auto-CAD II', 'Junior'): 'COET',
    ('GENG_304', 'Engineering Mechanics II (Dynamics)', 'Junior'): 'COET',
    ('GENG_306', 'Electrical Fundamental', 'Junior'): 'COET',
    ('GENG_306', 'Introduction to Engineering Analysis and Design', 'Junior'): 'COET',
    ('GENG_308', 'Strength of Material', 'Junior'): 'COET',
    ('GENG_308', 'Strength of Materials', 'Junior'): 'COET',
    ('GENG_400', 'Internship', 'Senior'): 'COET',
    ('GENG_404', 'Engineering Management II', 'Senior'): 'COET',
    ('GENG_408', 'Engineering Economics', 'Senior'): 'COET',
    ('GENG_408', 'Introduction to Thermodynamics', 'Senior'): 'COET',
    ('GENG_412', 'Research Methodology', 'Senior'): 'COET',
    ('GLE_202', 'Advance Glebo', 'Sophomore'): 'COAS',
    ('GLE_202', 'Advanced Glebo', 'Sophomore'): 'COAS',
    ('HIST_201', 'Liberian History and Society', 'Sophomore'): 'COAS',
    ('HIST_201', 'World History', 'Sophomore'): 'COAS',
    ('HIST_202', 'World History', 'Sophomore'): 'COAS',
    ('HIST_374', 'European History 11--The Renaissance To The Emergence of the Modern European States', 'Junior'): 'COAS',
    ('HIST_374', 'European History II: The Renaissance to the Emergence of the Modern European States', 'Junior'): 'COED',
    ('HIST_376', 'Post Colonial Africa', 'Junior'): 'COED',
    ('HIST_376', 'Post-Colonial Africa', 'Junior'): 'COAS',
    ('HIST_378', 'African Film, Arts and Politics', 'Junior'): 'COED',
    ('HIST_378', 'African Films, Arts and Politics', 'Junior'): 'COAS',
    ('HIST_472', 'Urbanization Of Contemporary Africa: Space, Identity & Politics', 'Senior'): 'COAS',
    ('HIST_472', 'Urbanization of Contemporary Africa: Space, Identity and Politics', 'Senior'): 'COED',
    ('HIST_475', 'Running While Others Walk: African Perspectives On Development', 'Senior'): 'COAS',
    ('HIST_475', 'Running While others Walk', 'Senior'): 'COED',
    ('HSC_202', 'Tropical and Communicable Diseases', 'Sophomore'): 'COHS',
    ('HSC_203', 'Human Nutrition', 'Sophomore'): 'COHS',
    ('HSC_204', 'Primary Health Care', 'Sophomore'): 'COHS',
    ('HSC_415', 'Health Systems Management', 'Senior'): 'COHS',
    ('HSM_202', 'Tropical and Communicable Diseases', 'Sophomore'): 'COHS',
    ('HSM_202', 'Tropical and communicable Diseases', 'Sophomore'): 'COHS',
    ('HSM_203', 'Human Nutrition', 'Sophomore'): 'COHS',
    ('HSM_203', 'Principal of Human Nutrition', 'Sophomore'): 'COHS',
    ('HSM_204', 'Primary Health Care and Concept', 'Sophomore'): 'COHS',
    ('HSM_204', 'Primary Health Care', 'Sophomore'): 'COHS',
    ('HSM_415', 'Health System Management (Health policy, Finance, and Regulation)', 'Senior'): 'COHS',
    ('HSM_415', 'Health Systems Management', 'Senior'): 'COHS',
    ('MATH_101', 'College Algebra', 'Freshmen'): 'COAS',
    ('MATH_102', 'Geometry & Trigonometry', 'Freshmen'): 'COAS',
    ('MATH_102', 'Geometry and Trigonometry', 'Freshmen'): 'COAS',
    ('MATH_202', 'Calculus II (Integral)', 'Sophomore'): 'COAS',
    ('MATH_202', 'Calculus II', 'Sophomore'): 'COAS',
    ('MATH_206', 'Introduction To Linear Algebra', 'Sophomore'): 'COAS',
    ('MATH_206', 'Introduction to Linear Algebra', 'Sophomore'): 'COAS',
    ('MATH_211', 'Calculus for Bio Students', 'Sophomore'): 'COAS',
    ('MATH_211', 'Calculus for Biology students', 'Sophomore'): 'COAS',
    ('MATH_302', 'Ordinary Deferential Equations (ODE)', 'Junior'): 'COET',
    ('MATH_302', 'Ordinary Differencial Equation', 'Junior'): 'COAS',
    ('MATH_376', 'Analytic Geometry', 'Junior'): 'COAS',
    ('MATH_376', 'Analytical Geometry', 'Junior'): 'COAS',
    ('MATH_377', 'Trigonometry', 'Junior'): 'COAS',
    ('MATH_378', 'Inferential Statistics', 'Junior'): 'COAS',
    ('MATH_474', 'Integral Calculus', 'Senior'): 'COAS',
    ('MATH_474', 'Intergral Calculus', 'Senior'): 'COAS',
    ('MATH_476', 'Linear Algebra for Secondary School Teachers', 'Senior'): 'COET',
    ('MATH_476', 'Linear Algebra', 'Senior'): 'COAS',
    ('MENG_302', 'Kinematics of Machanes', 'Junior'): 'COET',
    ('MENG_302', 'Kinematics of Machine', 'Junior'): 'COET',
    ('MENG_308', 'ME Basic Practical Workshop II', 'Junior'): 'COET',
    ('MENG_401', 'Engineering Thermodynamics', 'Senior'): 'COET',
    ('MENG_402', 'Heat Transfer', 'Senior'): 'COET',
    ('MENG_404', 'Fluid Machanics II', 'Senior'): 'COET',
    ('MENG_404', 'Fluid Mechanics II', 'Senior'): 'COET',
    ('MENG_406', 'Applied Themodynamics', 'Senior'): 'COET',
    ('MENG_406', 'Applied Thermodynamics', 'Senior'): 'COET',
    ('MENG_408', 'Dynamic System II', 'Senior'): 'COET',
    ('MENG_408', 'System Dynamics and Control', 'Senior'): 'COET',
    ('MENG_410', 'Mechincal Lab II', 'Senior'): 'COET',
    ('MENG_504', 'Fluid Power System', 'Senior'): 'COET',
    ('MENG_504', 'Fluid Power Systems', 'Senior'): 'COET',
    ('MENG_505', 'Mechanical Engineering Project Design', 'Senior'): 'COET',
    ('MENG_506', 'Production Management', 'Senior'): 'COET',
    ('MENG_508', 'HVAC/Modeling of Mechanical System', 'Senior'): 'COET',
    ('MENG_508', 'Heating, Ventilation, and Air Conditioning Systems', 'Senior'): 'COET',
    ('MENG_509', 'Machine Design II (Analysis and Design of Machine Components)', 'Senior'): 'COET',
    ('MENG_509', 'Machine Desin II', 'Senior'): 'COET',
    ('MENG_511', 'Internal Combustion Engine & Automotive Power Systems', 'Senior'): 'COET',
    ('MIDW_204', 'Advanced Pharmacology', 'Sophomore'): 'COHS',
    ('MIDW_204', 'Emergency Health and Disaster Response', 'Sophomore'): 'COHS',
    ('MIDW_306', 'Clinical Rotation II', 'Junior'): 'COET',
    ('MIDW_307', 'Clinical Affiliation and Senior Seminar', 'Junior'): 'COHS',
    ('MIDW_307', 'Clinical Affliation and Senior Seminar', 'Junior'): 'COHS',
    ('MIDW_311', 'Statistics for Midwives', 'Junior'): 'COHS',
    ('MIDW_402', 'Senior Seminar and Practicum (Clinical)', 'Senior'): 'COHS',
    ('NUR_200', 'Health Assessment with Lab', 'Sophomore'): 'COHS',
    ('NUR_202', 'Fundamentals of Nursing II with Lab & Clinical', 'Sophomore'): 'COHS',
    ('NUR_202', 'Fundamentals of Nursing II', 'Sophomore'): 'COHS',
    ('NUR_204', 'Clinical Pharmacology', 'Sophomore'): 'COHS',
    ('NUR_302', 'Medical Surgical Nursing II', 'Junior'): 'COHS',
    ('NUR_302', 'Medical-Surgical Nursing II with Lab & Clinical', 'Junior'): 'COHS',
    ('NUR_306', 'Obstetric Maternity II', 'Junior'): 'COHS',
    ('NUR_306', 'Obstetrics-Maternal Nursing II with Lab & Clinical', 'Junior'): 'COHS',
    ('NUR_308', 'Pediatric Nursing II with Clinical', 'Junior'): 'COHS',
    ('NUR_308', 'Pediatric Nursing II', 'Junior'): 'COHS',
    ('NUR_310', 'Evidnce-Based Nursing Research I', 'Junior'): 'COHS',
    ('NUR_310', 'Nursing Research I', 'Junior'): 'COHS',
    ('NUR_402', 'Ready for Practice Workshop', 'Senior'): 'COHS',
    ('NUR_402', 'Ready for Practics workshop', 'Senior'): 'COHS',
    ('NUR_404', 'Nursing Capstone Seminar', 'Senior'): 'COHS',
    ('NUR_404', 'Nursing Capstone seminar', 'Senior'): 'COHS',
    ('NUR_406', 'Nursing Clinical Affiliation', 'Senior'): 'COHS',
    ('NUR_406', 'Nursing clinical Affiliation II', 'Senior'): 'COHS',
    ('NUR_410', 'Human Pathophysiology', 'Senior'): 'COHS',
    ('PADM_202', 'Intro. to Public Admin. & Political Science', 'Sophomore'): 'COAB',
    ('PADM_202', 'Introduction to Public Administration', 'Sophomore'): 'COBA',
    ('PADM_304', 'Development Planning & Admin.', 'Junior'): 'COBA',
    ('PADM_304', 'Developmental Planning and Administration', 'Junior'): 'COAB',
    ('PADM_306', 'Administrative Law & Practice', 'Junior'): 'COBA',
    ('PADM_306', 'Adminstrative Law and Practice', 'Junior'): 'COAB',
    ('PADM_308', 'Public Organization Structure and Behavior', 'Junior'): 'COAB',
    ('PADM_308', 'Public Organizational Structure & Behavior', 'Junior'): 'COBA',
    ('PADM_402', 'Local Government and Rural Development Administration', 'Senior'): 'COAB',
    ('PADM_402', 'Rural Development Administration', 'Senior'): 'COBA',
    ('PADM_404', 'Government and Multinational Organizations', 'Senior'): 'COAB',
    ('PADM_404', 'Govt. and Multi National Organization', 'Senior'): 'COBA',
    ('PADM_420', 'Issues in Liberia and Africa Development', 'Senior'): 'COAB',
    ('PADM_420', 'Issues in Liberian & African Development', 'Senior'): 'COBA',
    ('PADM_430', 'Project Writing', 'Senior'): 'COBA',
    ('PE_102', 'Fitness and Wellness II', 'Freshmen'): 'COAS',
    ('PE_102', 'Fitness and Welness 11', 'Freshmen'): 'COAS',
    ('PHIL_101', 'Introduction to Philosophy', 'Freshmen'): 'COAS',
    ('PHYS_101', 'General Physic I', 'Freshmen'): 'COAS',
    ('PHYS_101', 'General Physics', 'Freshmen'): 'COAS',
    ('PHYS_202', 'Engineering Physics II', 'Sophomore'): 'COET',
    ('PHYS_202', 'Physics For Engineers II', 'Sophomore'): 'COET',
    ('PHY_202', 'Physics For Engineers II', 'Sophomore'): 'COET',    
    ('PH_202', 'Epidemiology', 'Sophomore'): 'COHS',
    ('PH_202', 'Introduction to Epidemiology and Liberian Healthcare System', 'Sophomore'): 'COHS',
    ('PH_302', 'Environmental Microbiology', 'Junior'): 'COHS',
    ('PH_304', 'Analytical Epidemiology', 'Junior'): 'COHS',
    ('PH_305', 'Biostatistics', 'Junior'): 'COHS',
    ('PH_305', 'Introduction to Biostatistics', 'Junior'): 'COHS',
    ('PH_306', 'Environmental & Occupational Health', 'Junior'): 'COHS',
    ('PH_306', 'Intro. To Environmental & Occupational Health', 'Junior'): 'COHS',
    ('PH_308', 'National & Global Health', 'Junior'): 'COHS',
    ('PH_308', 'National and Global Health Issues', 'Junior'): 'COHS',
    ('PH_312', 'Introduction to Health Policy and Management', 'Junior'): 'COHS',
    ('PH_312', 'Introduction to Health Policy and Managenment', 'Junior'): 'COHS',
    ('PH_314', 'Analysis of Environmental Data', 'Junior'): 'COHS',
    ('PH_316', 'Infectious Disease Epidemiology', 'Junior'): 'COHS',
    ('PH_316', 'Infectious Diseases Epidemiology', 'Junior'): 'COHS',
    ('PH_320', 'Sex, Public Policy and the Law', 'Junior'): 'COHS',
    ('PH_320', 'Sex,Public Policy & the Law', 'Junior'): 'COHS',
    ('PH_40', 'Internship', 'Senior'): 'COHS',
    ('PH_401', 'Special Topics in Public Health', 'Senior'): 'COHS',
    ('PH_403', 'Public Health Research II', 'Senior'): 'COHS',
    ('PH_406', 'Senior Seminar', 'Senior'): 'COHS',
    ('PH_408', 'Internship', 'Senior'): 'COHS',
    ('PH_413', 'Emmergency & Disaster Preparedness', 'Senior'): 'COHS',
    ('PH_414', 'Health Economics', 'Senior'): 'COHS',
    ('PH_414A', 'Health Economics', 'Senior'): 'COHS',
    ('PH_416', 'Gender, Race and Ethnicity', 'Senior'): 'COHS',
    ('PH_416', 'Gender,Race, and Ethnicity', 'Senior'): 'COHS',
    ('PH_417', 'Healthy People', 'Senior'): 'COHS',
    ('PH_418', 'Emergency Disaster Preparedness', 'Senior'): 'COHS',
    ('PH_423', 'Applied Epidemiology and Statistics (EM)', 'Senior'): 'COHS',
    ('PH_423', 'Applied Epidemiology and Statistics with Lab', 'Senior'): 'COHS',
    ('PH_425', 'Health Behavior and Risk Reduction', 'Senior'): 'COHS',
    ('PH_433', 'Applied Epidemiology and Statistics (Lab)', 'Senior'): 'COHS',
    ('PSY_101', 'Introduction to Psychology', 'Freshmen'): 'COAS',
    ('PSY_102', 'Developmental Psychology', 'Freshmen'): 'COAS',
}

course_prefix_college = {
    'ACCT': 'COBA',
    'AGR': 'CFAS',
    'BFIN': 'COBA',
    'BIO': 'COAS',
    'BUSA': 'COBA',
    'CENG': 'COET',
    'CHEM': 'COAS',
    'CSENG': 'COET',
    'ECD': 'COED',
    'ECON': 'COBA',
    'EDU': 'COED',
    'EED': 'COED',
    'EENG': 'COET',
    'ENGL': 'COAS',
    'ENVS': 'COAS',
    'GENG': 'COET',
    'HSM': 'COHS',
    'MATH': 'COAS',
    'MENG': 'COET',
    'MIDW': 'COHS',
    'NUR': 'COHS',
    'PADM': 'COBA',
    'PE': 'COED',
    'PH': 'COHS',
    'PHIL': 'COAS',
    'PHYS': 'COAS',
    'PSY': 'COAS',
}

course_code_mapping = {"ENG": "ENGL", "MID": "MIDW", "HSC": "HSM"}
